### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ghost** [LeeSunBowen/GitHub521#2]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\update.py", line 113, in <module>
    main()
  File "C:\Users\Administrator\Desktop\update.py", line 108, in main
    writehosts(old_hosts, hosts_content, hostsfile)
  File "C:\Users\Administrator\Desktop\update.py", line 82, in writehosts
    for i in range(startline,endline+1)[::-1]:
UnboundLocalError: local variable 'startline' referenced before assignment

**Comment by Bowen1911** [comment]
auto_host_change.py脚本中74行开始的函数如下：
```
def writehosts(old_hosts, content, hostsfile):
    #删除老hosts中的ip
    for line in range(len(old_hosts)):
        if '# GitHub Host Start' in old_hosts[line]:
            startline = line
        if '# GitHub Host End' in old_hosts[line]:
            endline = line
            break
```
解决这个错误需要满足两个条件，一个是给予程序权限修改host，另一个是要自己手动在原来的host文件中写入文本：`# GitHub Host Start`和`# GitHub Host End`，否则程序无法定位到行。
最简单的解决方案是按照这个repositories里面的host文件的文本内容覆盖替换自己的host的内容，主要是需要加上最后一段的：
```
# GitHub Host Start
183.131.184.76                github.githubassets.com
199.232.68.133                camo.githubusercontent.com
199.232.68.133                github.map.fastly.net
199.232.69.194                github.global.ssl.fastly.net
140.82.112.3                  github.com
140.82.112.6                  api.github.com
199.232.68.133                raw.githubusercontent.com
199.232.68.133                user-images.githubusercontent.com
199.232.68.133                favicons.githubusercontent.com
199.232.68.133                avatars5.githubusercontent.com
199.232.68.133                avatars4.githubusercontent.com
199.232.68.133                avatars3.githubusercontent.com
199.232.68.133                avatars2.githubusercontent.com
199.232.68.133                avatars1.githubusercontent.com
199.232.68.133                avatars0.githubusercontent.com
140.82.114.4                  gist.github.com

# GitHub Host End
```
用于定位

**Comment by ghost** [comment]
![](https://raw.githubusercontent.com/ctbt-mg/logo/master/%E6%8D%95%E8%8E%B7.PNG)
@Aegis1863

**Comment by Bowen1911** [comment]
并不是每次更新了host就可以立即生效，就算手动改也是一样的，只能保证人不干预的情况下，直接进去的概率大一些
